index:
  path: /
  controller: App\Controller\MainController::index

cv:
  path: /curriculum-vitae
  controller: App\Controller\MainController::curriculumVitae

contact:
  path: /contact
  controller: App\Controller\MainController::contact
